### ISSUE TITLE
[Feature] Use Certificate from file instead of generating a new one every run

### ISSUE THREAD

**Issue by mcjcloud** [hatoo/http-mitm-proxy#4]
As of 0.4.0, it appears the only way to start the proxy with SSL decryption is to provide a `rcgen::Certificate`. The `rcgen` library only supports generating certs and not reading them. It would be useful to have the ability to reuse an existing cert so I don't have to trust the new one each time.

If there's a way to do this already please let me know :)

**Comment by hatoo** [comment]
Because https://docs.rs/rcgen/latest/rcgen/struct.Certificate.html#method.serialize_der_with_signer requires `rcgen::Certificate`, we must create `rcgen::Certificate` by existing cert.

This can be done by enabling `rcgen`'s `x509-parser` feature. I've updated the `proxy` example to demonstrate how to create `rcgen::Certificate` from existing files.

I hope the example helps you.
